name: deploy to qiniu
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
        path: master
    - uses: Hanlin-Dong/hexo-to-qiniu-action@v1
      with:
        bucket: picpools
        access-key: ${{ secrets.QINIU_ACCESS_KEY }}
        secret-key: ${{ secrets.QINIU_SECRET_KEY }}
        base-folder: ../master
        domain: "http://pic.longtao.fun"
        sub-domain: ""
